version: "3.8"
services:
  postgres-9999:
    image: postgres:13
    environment:
      POSTGRES_USER: vteachersadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vteachersapi
    ports:
      - '9999:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

volumes:
  db:
