version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

  notes-app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '443:443'
    environment:
      DB_HOST: postgres
      PROTOCOL: 'https:'
      SEARCH: 'studywithme,study-with-me,study%20with%20me'
    volumes:
      - ./notes:/opt/notes-app/notes
      - ./public:/opt/notes-app/public
      - ./scripts:/opt/notes-app/scripts
      - ./server:/opt/notes-app/server
      - ./src:/opt/notes-app/src
      - ./credentials.js:/opt/notes-app/credentials.js

volumes:
  db:
