version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: notesadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesapi
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - db:/var/lib/postgresql/data

  notes-app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - '443:443'
    environment:
      DB_HOST: postgres
      PROTOCOL: 'https:'
      SEARCH: '%E3%83%A9%E3%82%A4%E3%83%96%E3%82%AB%E3%83%A1%E3%83%A9,cam,camera,dashcam,dash-cam,vteacher'
    volumes:
      - ./notes:/opt/notes-app/notes
      - ./public:/opt/notes-app/public
      - ./scripts:/opt/notes-app/scripts
      - ./server:/opt/notes-app/server
      - ./src:/opt/notes-app/src
      - ./credentials.js:/opt/notes-app/credentials.js
      - ./privkey.pem:/opt/notes-app/server/privkey.pem
      - ./fullchain.pem:/opt/notes-app/server/fullchain.pem
      - ./settings.js:/opt/notes-app/settings.js

volumes:
  db:
